# Generated by Django 4.2.2 on 2023-06-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_book_created_at_book_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="Description",
            new_name="description",
        ),
    ]
