# Generated by Django 4.2.2 on 2023-06-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.AlterField(
            model_name="book",
            name="book_image",
            field=models.ImageField(blank=True, upload_to="book/static/images"),
        ),
    ]
